export const dashboardStyles = {
  container: "min-h-screen bg-slate-950 text-white p-6 space-y-8 animate-in fade-in duration-500",
  section: "space-y-6",
  card: "bg-slate-900/50 backdrop-blur-sm border border-slate-800 rounded-xl shadow-lg hover:shadow-2xl transition-all duration-300 p-6",
  cardHeader: "flex items-center justify-between mb-4",
  cardTitle: "text-lg font-semibold text-slate-100",
  metricValue: "text-3xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-white to-slate-400",
  metricLabel: "text-sm text-slate-400 font-medium uppercase tracking-wider",
  iconContainer: "p-3 rounded-lg bg-slate-800/50 text-slate-300",
  grid: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6",
  filterPanel: "bg-slate-900/80 border border-slate-800 rounded-xl p-4 flex flex-col md:flex-row gap-4 items-end md:items-center justify-between sticky top-4 z-10 backdrop-blur-md shadow-2xl",
  chartContainer: "h-[350px] w-full mt-4",
  tableContainer: "overflow-hidden rounded-lg border border-slate-800",
  tableHeader: "bg-slate-950 text-slate-400 text-xs uppercase font-semibold",
  tableRow: "border-b border-slate-800 hover:bg-slate-800/30 transition-colors",
  tableCell: "p-4 text-sm text-slate-300",
  badge: "px-2 py-1 rounded text-xs font-medium border inline-flex items-center",
  badgeSuccess: "bg-green-500/10 text-green-400 border-green-500/20",
  badgeWarning: "bg-yellow-500/10 text-yellow-400 border-yellow-500/20",
  badgeError: "bg-red-500/10 text-red-400 border-red-500/20",
  badgeInfo: "bg-blue-500/10 text-blue-400 border-blue-500/20",
};