export const dashboardStyles = {
  container: "min-h-screen bg-[var(--tenant-bg)] text-[var(--tenant-text)] p-6 space-y-8 animate-in fade-in duration-500",
  section: "space-y-6",
  card: "bg-[var(--tenant-surface)] backdrop-blur-sm border border-[var(--tenant-line)] rounded-xl shadow-sm hover:shadow-md transition-all duration-300 p-6",
  cardHeader: "flex items-center justify-between mb-4",
  cardTitle: "text-lg font-semibold text-[var(--tenant-text)]",
  metricValue: "text-3xl font-bold text-[var(--tenant-text)] tracking-tight",
  metricLabel: "text-sm text-[var(--tenant-muted)] font-medium uppercase tracking-wider",
  iconContainer: "p-3 rounded-lg bg-[var(--tenant-bg-2)] text-[var(--tenant-muted)]",
  grid: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6",
  filterPanel: "bg-[var(--tenant-surface)] border border-[var(--tenant-line)] rounded-xl p-4 flex flex-col md:flex-row gap-4 items-end md:items-center justify-between sticky top-4 z-10 backdrop-blur-md shadow-sm",
  chartContainer: "h-[350px] w-full mt-4",
  tableContainer: "overflow-hidden rounded-lg border border-[var(--tenant-line)]",
  tableHeader: "bg-[var(--tenant-bg-2)] text-[var(--tenant-muted)] text-xs uppercase font-semibold",
  tableRow: "border-b border-[var(--tenant-line)] hover:bg-[color-mix(in_srgb,var(--brand-primary)_6%,transparent)] transition-colors",
  tableCell: "p-4 text-sm text-[var(--tenant-text)]",
  badge: "px-2 py-1 rounded text-xs font-medium border inline-flex items-center",
  badgeSuccess: "bg-green-500/10 text-green-400 border-green-500/20",
  badgeWarning: "bg-yellow-500/10 text-yellow-400 border-yellow-500/20",
  badgeError: "bg-red-500/10 text-red-400 border-red-500/20",
  badgeInfo: "bg-blue-500/10 text-blue-400 border-blue-500/20",
};
